---
- name: Download latest artifacts from Jfrog
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    # Pass these via CLI (-e "artifactory_user=... artifactory_password=...") or set defaults here
    #-e artifactory_user=${ARTIFACTORY_USER} -e artifactory_password=${ARTIFACTORY_PASS}
    #artifactory_user: "admin"
    #artifactory_password: "Honda@2563#"

  tasks:
    - name: "check Directory"
      stat:
        path: "/home/laxman/SDN/{{ sdn_version }}"
      register: sdn_folder

    - name: "echo if directory already existed"
      debug:
        msg: "the /home/laxman/SDN/{{ sdn_version }} directory already exists"
      when: sdn_folder.stat.exists

    - name: create directory if not exists
      file:
        path: "/home/laxman/SDN/{{ sdn_version }}"
        state: directory
        mode: '0755'
        group: laxman
        owner: laxman
      when: not sdn_folder.stat.exists

    - name: download artifacts list
      uri:
        url: "http://192.168.64.1:8082/artifactory/gradle-release-local/com/wsgc/SDNs/{{ sdn_version }}/"
        method: GET
        user: "{{ artifactory_user }}"
        password: "{{ artifactory_password }}"
        force_basic_auth: true
        return_content: true
        validate_certs: false
      register: response

    - name: Extract file links
      set_fact:
        file_links: "{{ response.content | regex_findall('href=\"([^\"]+)\"') }}"

    - name: download files
      get_url:
        url: "http://192.168.64.1:8082/artifactory/gradle-release-local/com/wsgc/SDNs/{{ sdn_version }}/{{ item }}"
        dest: "/home/laxman/SDN/{{ sdn_version }}/{{ item }}"
        url_username: "{{ artifactory_user }}"
        url_password: "{{ artifactory_password }}"
        force_basic_auth: true
        validate_certs: false
      loop: "{{ file_links }}"
      ignore_errors: true
