---
- name: Download latest artifacts from Jfrog
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
   - name: "check Directory"
     stat:
      path: "/opt/SDN/{{ sdn_version }}"
      register: sdn_folder

   - name: "echo if directory already existed"
     debug:
      msg: "the  /opt/SDN/{{ sdn_version }} directory is already existed
      when: sdn_folder.stat.exists

    - name: create directory if not exists
      file:
        path: "/opt/SDN/{{ sdn_version }}"
        state: directory
        mode: 0755
        group: unixusers
        owner: shivam
        when: sdn_folder.stat.exists == false

     - meta: end_host
       when: sdn_folder.stat.exists

     - name: download artifacts
       uri:
         url: "https://snapshotrepo.wsgc.com/artifactory/gradle-release-local/com/wsgc/SDNs/{{ sdn_version }}/"
         method: GET
         return content: yes
         validate_certs: false
         register: response
         
      - name: Extract file links
        set_fact:
          file_links: "{{ response.content | regex_findall('(7<=<a href=\") [^\"]+(?=\")') }}"

      - name: download files
        uri:
          url: "https://snapshotrepo.wsgc.com/artifactory/gradle-release-local/com/wsgc/SDNs/{{ sdn_version }}/{{ item }}"
          dest: "/apps/scope/SDN/{{ sdn_version }}/{{ item }}"
          method: GET
          validate_certs: false
          loop: "{{ file_links }}"
          ignore_errors: yes
